### ISSUE TITLE
unable to run tests

### ISSUE THREAD

**Issue by salus-sage** [glynnbird/birdreader#35]
i installed mocha and tried to run the tests but it failed, below is the log..

``` module.js:487
    throw err;
    ^

Error: Cannot find module 'should'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (H:\Projects\newExperiments\birdreader\test\api.js:5:12)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at C:\Users\salus\AppData\Roaming\nvm\v8.0.0\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Users\salus\AppData\Roaming\nvm\v8.0.0\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (C:\Users\salus\AppData\Roaming\nvm\v8.0.0\node_modules\mocha\lib\mocha.js:536:10)
    at Object.<anonymous> (C:\Users\salus\AppData\Roaming\nvm\v8.0.0\node_modules\mocha\bin\_mocha:573:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by salus-sage** [comment]
ok it worked after installing should.
